nameOverride: ""
fullnameOverride: ""
# Default values for flask-app
replicaCount: 1

# Prometheus monitoring configuration
prometheus:
  enabled: false  # Set to true to enable Prometheus monitoring

image:
  repository: flask-demo-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 5001

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

env:
  - name: ENVIRONMENT
    value: "production"

livenessProbe:
  httpGet:
    path: /api/status
    port: 5001
  initialDelaySeconds: 30
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /api/status
    port: 5001
  initialDelaySeconds: 5
  periodSeconds: 5
